### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [bobrowskibiz/rock-paper-scissors#1]
- [x] zmien czerwone tlo na cos bardziej przyjemnego dla oka
- [x] masz trzy funkcje `playerPick` - wybierz jedna
- [x] usun console logi
- [x] w przypadku wygranej gracza, w alercie wypisz tez jego imie
- [x] niech wciecia w js beda spojne - albo 2 spacje, albo 4
- [x] jesli gra jest w jezyku polskim, to niech wszystkie komunikaty beda po polsku

**Comment by bobrowskibiz** [comment]
chyba wszystko cacy

**Comment by zdolny** [comment]
- [ ] komunikaty w j. polskim: https://scr.hu/oL3Lzg
- [ ] zamiast pobierac z widoku imie gracza podczas wyswietlania wygranej w meczu, wypisz je z wlasnosci obiektu, gdzie jest przechowywane

**Comment by bobrowskibiz** [comment]
pozmieniane
